version: '3.8'

services:
  # There are defined conainers
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /bin/sh -c "echo 'Symfony app running at http://localhost:8000' && php -S 0.0.0.0:8000 -t public"

  db:
    image: mariadb:10.6
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
